language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
  - cd ..
  - git clone https://github.com/catalyst-cooperative/pudl.git
  - cd pudl
  - pip install -e .
  - cd ../PowerGenome
  - pip install codecov pytest-cov
# command to run tests
script:
  - pytest --cov=powergenome tests/
# env:
#     - CODECOV_TOKEN=23fb74a3-a3dc-44c5-be81-6958c4ca6a21
after_success:
- codecov --token=23fb74a3-a3dc-44c5-be81-6958c4ca6a21
