name: powergenome-test2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7 # Remove for tox.ini & setup.py
  - pip
  - conda-forge::catalystcoop.pudl=0.3
  - jupyterlab
  - black
  - pytest
  - requests
  - beautifulsoup4
  - pyyaml
  - conda-forge::pre-commit
  - isort

  # GIS dependencies from conda-forge
  - conda-forge::fiona
  - conda-forge::geopandas
  - conda-forge::shapely
  - conda-forge::descartes

  - pip:
    - python-dotenv
    - cpi
    - flatten-dict
