name: Run GenX

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        repository: GenXProject/GenX
        ref: main
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - run: julia -e 'println("Hello, World!")'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1